from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

def build_pdf(title: str, sections: list[tuple[str,str]]):
    buf=BytesIO(); doc=SimpleDocTemplate(buf,pagesize=A4,rightMargin=36,leftMargin=36,topMargin=40,bottomMargin=40)
    styles=getSampleStyleSheet(); story=[Paragraph("CLAIMX",styles["Title"]),Paragraph(title,styles["Heading2"]),Spacer(1,12)]
    for heading, body in sections:
        story += [Paragraph(heading,styles["Heading3"]), Paragraph(body.replace("\n","<br/>"),styles["BodyText"]), Spacer(1,8)]
    story.append(Spacer(1,12)); story.append(Paragraph("Generated by CLAIMX — AI-generated information requires human verification.", styles["Italic"]))
    doc.build(story); buf.seek(0); return buf
